config/routes.rb
ConferenceAttendance::Application.routes.draw do

  root :to => "talks#index"

  resources :talks
  resources :attendees
  resources :attendances

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  belongs_to :attendee
  belongs_to :talk

  attr_accessible :presenter, :talk_id, :attendee_id

  validates :attendee, :presence => true
  validates :talk, :presence => true
end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  has_many :attendances
  has_many :talks, :through => :attendances

  attr_accessible :affiliation, :email, :name

  validates :name, :presence => true
  validates :email, :presence => true, :uniqueness => true
end

app/models/talk.rb
class Talk < ActiveRecord::Base
  has_many :attendances
  has_many :attendees, :through => :attendances

  attr_accessible :description, :room, :speaker, :title

  validates :title, :presence => true
  validates :room, :presence => true
  validates :speaker, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_filter :find_talks_and_attendees, only: [:new, :create]

  def new
    if @attendees.size == 0
      flash[:alert] = "There are not attendees to be added to talks."
      redirect_to attendees_path
    else
      @attendance = Attendance.new
    end
  end

  def create
    @attendance = Attendance.new(params[:attendance])
    if @attendance.save
      flash[:notice] = "Attendance has been created."
      redirect_to @attendance.talk
    else
      flash[:alert] = "Attendance has not been created."
      redirect_to talks_path
    end
  end

  def destroy
    @attendance = Attendance.find(params[:id])
    @attendance.destroy
    flash[:notice] = "Talk attendance has been deleted."
    redirect_to talks_path
  end

private
  def find_talks_and_attendees
    @talks = Talk.all
    @attendees = Attendee.all
  end
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
before_filter :find_attendee, :only => [:show, :edit, :update, :destroy]

  def index
    @attendees = Attendee.all
  end

  def new
    @attendee = Attendee.new
  end

  def create
    @attendee = Attendee.new(params[:attendee])
    if @attendee.save
      flash[:notice] = "Attendee has been created."
      redirect_to @attendee
    else
      flash[:alert] = "Attendee has not been created."
      render :action => "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @attendee.update_attributes(params[:attendee])
      flash[:notice] = "Attendee has been updated."
      redirect_to @attendee
    else
      flash[:alert] = "Attendee has not been updated."
      render :action => "edit"
    end
  end

  def destroy
    @attendee.destroy
    flash[:notice] = "Attendee has been deleted."
    redirect_to attendees_path
  end

private
  def find_attendee
    @attendee = Attendee.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The attendee you were looking for could not be found."
      redirect_to attendees_path
  end
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
before_filter :find_talk, :only => [:show, :edit, :update, :destroy]

  def index
    @talks = Talk.all
  end

  def new
    @talk = Talk.new
  end

  def create
    @talk = Talk.new(params[:talk])
    if @talk.save
      flash[:notice] = "Talk has been created."
      redirect_to @talk
    else
      flash[:alert] = "Talk has not been created."
      render :action => "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @talk.update_attributes(params[:talk])
      flash[:notice] = "Talk has been updated."
      redirect_to @talk
    else
      flash[:alert] = "Talk has not been updated."
      render :action => "edit"
    end
  end

  def destroy
    @talk.destroy
    flash[:notice] = "Talk has been deleted."
    redirect_to talks_path
  end

private
  def find_talk
    @talk = Talk.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The talk you were looking for could not be found."
      redirect_to talks_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "Conference Attendance Management").join(" - ")
      end
    end
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/views/attendances/new.html.erb
<h2>Add Talk Attendances</h2>

<%= form_for(@attendance) do |f| %>
  <p>
  <%= f.label :talk, "Talk" %>
  <% talks = @talks.map {|talk| [talk.title, talk.id] }%>
  <%= f.select(:talk_id, options_for_select(talks)) %> <br>

  <%= f.label :presenter, "Presenter" %>
  <%= f.radio_button :presenter, :true %><label>Yes</label>
  <%= f.radio_button :presenter, :false, checked: true %><label>No</label>
  </p>

  <p>
  <%= f.label :attendee, "Attendee" %>
  <% attendees = @attendees.map {|attendee| [attendee.name, attendee.id] }%>
  <%= f.select(:attendee_id, options_for_select(attendees)) %> <br>
  </p>

  <%= f.submit "Submit" %>

<% end -%>

app/views/attendees/_form.html.erb
<h2>New Attendee</h2>
<%= form_for(@attendee) do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :affiliation %><br />
    <%= f.text_field :affiliation %>
  </p>

  <%= f.submit %>
<% end %>

app/views/attendees/edit.html.erb
<h2>Edit Attendee</h2>
<%= render "form" %>

app/views/attendees/index.html.erb
<%= link_to "New Attendee", new_attendee_path %>
<br>
<br>
<h2>Attendees</h2>
<br>
<ul>
  <% @attendees.each do |attendee| %>
    <li><%= link_to attendee.name, attendee %></li>
    <br>
  <% end %>
</ul>

app/views/attendees/new.html.erb
<%= render "form" %>

app/views/attendees/show.html.erb
<% title(@attendee.name, "Attendees") %>
<h2><%= @attendee.name %> </h2>
Email: <%= @attendee.email %> |
Affiliation: <%= @attendee.affiliation %>
<br>
<br>
<%= link_to "Edit Attendee", edit_attendee_path(@attendee) %> |
<%= link_to "Delete Attendee", attendee_path(@attendee),
    :method => :delete,
    :confirm => "Are you sure you want to delete this attendee?" %>
<br>
<br>
<h4>Attended talks:</h4>
<br>
<ul style="height: 50px">
  <% @attendee.talks.each do |talk| %>
    <li style="height: 25px"><%= link_to talk.title, talk_path %>  |
      <% talk.attendances.each do |attendance| %>
        <% if attendance.attendee_id == @attendee.id %>
          <%= link_to "Remove Talk", attendance_path(attendance),
            :method => :delete,
            :confirm => "Are you sure you want to remove this talk from attended talks?" %> </li>
        <% end %>
      <% end %>
  <% end %>
</ul>

<br>
<div>
  <%= link_to "Add Talk", new_attendance_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <% if content_for?(:title) %>
      <%= yield(:title) %>
    <% else %>
      Conference Attendance
    <% end %>
  </title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <h1>Conference Attendance Management</h1>
  <br>

  <% flash.each do |key, value| %>
    <div class='flash' id='<%= key %>'>
      <%= value %>
    </div>
  <% end %>

  <br>

<%= yield %>

  <br>
  <br>
  <div>
    <hr>
    <%= link_to "See all talks", talks_path(:talk) %> |
    <%= link_to "See all attendees", attendees_path(:attendee) %>
  </div>

</body>
</html>

app/views/talks/_form.html.erb
<h2>New Talk</h2>
<%= form_for(@talk) do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :room %><br />
    <%= f.text_field :room %>
  </p>

  <p>
    <%= f.label :speaker %><br />
    <%= f.text_field :speaker %>
  </p>

  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <%= f.submit %>
<% end %>

app/views/talks/edit.html.erb
<h2>Edit Talk</h2>
<%= render "form" %>

app/views/talks/index.html.erb
<%= link_to "New Talk", new_talk_path %>
<br>
<br>
<h2>Talks</h2>
<br>
<ul>
  <br>
  <% @talks.each do |talk| %>
    <li><%= link_to talk.title, talk %></li>
    <br>
  <% end %>
</ul>

app/views/talks/new.html.erb
<%= render "form" %>

app/views/talks/show.html.erb
<% title(@talk.title, "Talks") %>
<h2><%= @talk.title %> </h2>
Room: <%= @talk.room %> |
Description: <p><%= simple_format(@talk.description) %></p>
<br>
<br>
<%= link_to "Edit Talk", edit_talk_path(@talk) %> |
<%= link_to "Delete Talk", talk_path(@talk), :method => :delete,
:confirm => "Are you sure you want to delete this talk?" %>
<br>
<br>
<h4>Attendees:</h4>
<br>
<ul style="height: 50px">
  <% @talk.attendees.each do |attendee| %>
    <li style="height: 25px"><%= link_to attendee.name, attendee_path %>  |
      <% attendee.attendances.each do |attendance| %>
        <% if attendance.talk_id == @talk.id %>
          <% if attendance.presenter? %>
            --> Speaker |
          <% end %>
          <%= link_to "Remove Attendee", attendance_path(attendance),
            :method => :delete,
            :confirm => "Are you sure you want to remove this attendee?" %> </li>
        <% end %>
      <% end %>
  <% end %>
</ul>

<br>
<div>
  <%= link_to "Add Attendee", new_attendance_path %>
</div>